### ISSUE TITLE
Row and event bar height

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#11]
Another formatting feature: is it possible to enable the user to control the height of the rows and corresponding timeline bars? It is probably not necessary to be able to set each one individually, but it would be a useful feature to be able to set the default value for all rows/bars.

**Comment by dankelley** [comment]
Not presently. This is set by the geometry of the plot device.  The best approach might be to resize it in an interactive session and then call `png()` or `pdf()` before repeating it. This is how I do most of my work, and I think most people work that way in R ... as you get close to the results you want, start saving plots in files.  (It's a bit analogous to how most people use R: type a few simple things in the console, but start copy-pasting them into a file early on, and then working in that file.)
