### ISSUE TITLE
Format Y-labels

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#12]
Is there a way to left-justify Y labels and indent text on non-header rows so that the Ylabel items appear in a typical list format? 

Header row     (no timeline bar)
     Item 1        (timeline bar)
     Item 2        (timeline bar) etc..

**Comment by dankelley** [comment]
This has been added and documented. See `?"plot,gantt-method"`. The documentation includes examples, and a caveat for OSX-RStudio windows. I am closing this.
