### ISSUE TITLE
Plot formatting improvements

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#14]
- [x]  The top item in the list of events seems to be bold no matter what - maybe this has to do with my code (yes, it was your code: you had set `font` to have bold-face, numerical value 2, for the first item and then 1 for the others).
- [x] The forward and back arrows on the event bars have different colors than the bars themselves - they should be the same (fixed)
- [ ] The thickness of bars depends on the number of bars - This should really be fixed according to user-provided parameter value.
- [ ]  On the top, the text corresponding to the event lines should appear in an empty top row within the box of the gantt chart. Right now it sits on top outside of the box
- [ ] Dotted event lines should start just beneath event text, not top of box
- [x] Allow repositioning of title. Right now it seems to get placed pretty far away from plot.

**Comment by dankelley** [comment]
Below is a code that the reporter sent by email. (I post it here so I don't have to retain that email.)
```R
#GET PLAN
require(devtools)
remove.packages(plan)
install_github("dankelley/plan")

#INSTALL LIBRARIES
install.packages(XLConnect)
library(XLConnect)

#MAKE DATAFRAME FROM EXCEL
mydf <- data.frame(readWorksheetFromFile("/path/to/mydata.xlsx", sheet=1))

#MAKE GANTT OBJECT
mygantt <- as.gantt(mydf[,1], mydf[,2], mydf[,3], mydf[,4], mydf[,5], mydf[,6])

#PLOTTING WINDOW
quartz("Quartz", width=8.5, height=3.5, pointsize=14)

#PLOT GANTT OBJECT
plot(mygantt, event.time = mydf$event.time, event.label = mydf$event.name, event.side = 3,  col.connector = "black", col.done = topo.colors(12), col.notdone = topo.colors(12), col.eventLine = mydf$event.line.color, col.event = mydf$event.name.color,  cex.event = 0.5, font.event = par("font"),
lty.eventLine = "dashed", lwd.eventLine = 0.1, bg = par("bg"),
grid.col = "lightgray", grid.lty = "dotted", ylabels = list(col = 1, cex
= mydf$header.font, font=c(2, rep(1,11)), justification = mydf$indent), arrows = mydf$arrows, main = "Project Timeline - draft 1 Sept 25 2016", cex.main = par("cex"))
```

**Comment by dankelley** [comment]
@marcel111 -- can you email me a CSV file of your data? I cannot get XLConnect to work. The error message is given below ... but I really don't care whether I can get that working because having xls work on my machine is not a high priority for me.
```R
> library(XLConnect)
Loading required package: XLConnectJars
Error : .onLoad failed in loadNamespace() for 'XLConnectJars', details:
  call: .jinit()
  error: JNI_GetCreatedJavaVMs returned -1

Error: package ‘XLConnectJars’ could not be loaded
```

**Comment by dankelley** [comment]
Thanks for sending the `.csv` file. I am still having problems, but I'm posting a code that at least reads this `.csv` file. I had to play some tricks to make it decode the US-style dates (which are ambiguous, so R needs a hint for decoding them). I'm posting an updated test code here. I will likely not look at this for a few weeks, and the point of posting my test code is so that I can come back to it fairly easily later.
```R
library(plan)

mydf <- read.csv("exampleGanttData.csv")
as.time <- function(x)
    as.POSIXct(x, format="%m/%d/%y") # American excel style

warning("ignoring mydf$NeededBy, which is supposed to be an integer, not a time\n")
warning("had to write a function to decode American excel time format\n")

mygantt <- as.gantt(key=mydf$Key, description=mydf$task,
                    start=as.time(mydf$Start), end=as.time(mydf$End), done=mydf$done)# , neededBy=mydf$NeededBy)

plot(mygantt, event.time = as.time(mydf$event.time), event.label = mydf$event.name, event.side = 3,  
    col.connector = "black", col.done = topo.colors(12), col.notdone = topo.colors(12), 
    col.eventLine = mydf$event.line.color, col.event = mydf$event.name.color,  cex.event = 0.5, 
    font.event = par("font"), lty.eventLine = "dashed", lwd.eventLine = 0.1, bg = par("bg"),
    grid.col = "lightgray", grid.lty = "dotted", ylabels = list(col = 1,
    cex= mydf$header.font, font=c(2, rep(1,11)), justification = mydf$indent), 
    arrows = mydf$arrows, main = "Project Timeline - draft 1 Sept 25 2016", 
    cex.main = par("cex"))
```

**Comment by dankelley** [comment]
Below are the contents of the test datafile (provided with permission of reporter):
```
Key,task,Start,End,Done,NeededBy,task.color,event.time,event.name,header,header.font,header.bold,indent,event.name.color,event.line.color,arrows
1,Test Header 1,9/10/15,9/10/15,0,3/27/16,0,9/10/15,text1,0,1.2,2,0,1,1,neither
2,Complete Protocol Draft,9/10/15,10/1/15,90,3/27/16,1,10/1/15,text2,1,1,1,1,1,1,right
3,Review protocol,10/1/15,10/14/15,0,3/27/16,1,10/14/15,text3,1,1,1,1,1,1,right
4,Prepare study docs,10/1/15,12/15/15,0,3/27/16,1,12/15/15,text4,1,1,1,1,1,1,right
5,Test Header 2,10/14/15,10/14/15,0,3/27/16,2,10/21/15,text5,0,1.2,2,0,2,2,right
6,Protocol review 1,10/21/15,12/15/15,0,3/27/16,3,12/15/15,text6,3,1,1,1,1,1,left
7,Develop Database,11/1/15,1/15/16,0,3/27/16,1,1/15/16,text7,1,1,1,1,1,1,both
8,Protocol revision 2,12/15/15,1/4/16,0,3/27/16,1,1/4/16,text8,1,1,1,1,1,1,both
9,Protocol review 2,1/4/16,2/14/16,0,3/27/16,1,2/14/16,text9,1,1,1,1,1,1,neither
10,Study approval,2/14/16,2/16/16,100,3/27/16,1,2/16/16,text10,1,1,1,1,1,1,neither
11,Conduct Study,3/1/16,6/29/16,0,3/27/16,1,6/29/16,text11,1,1,1,1,1,1,neither
```

**Comment by dankelley** [comment]
Below is a marked-up version of the plot from the test file, with the reporter's suggestions. (This sort of diagram is very helpful for bug reports!!)
![example_gantt_plot_suggestions](https://cloud.githubusercontent.com/assets/99469/19056633/db1fa372-89a0-11e6-8a31-6e2664fa12f3.png)

**Comment by dankelley** [comment]
Re your first task -- yes, it was your code: you had set font to have bold-face, numerical value 2, for the first item and then 1 for the others.

**Comment by dankelley** [comment]
Re the triangles -- I think they are ok now. This is in `master` branch, commit b23ded176e92ddc3912e8fa299a8a597fa392b36 and I recommend the reporter try that out. I've ticked off the top two items in the checklist at the top of this issue. Also, please note that as I work on my test code, I will occasionally edit the comment above in which I present that code. I will probably not look at this again until the weekend.

**Comment by dankelley** [comment]
The title is now closer to the plot. Also, there is a new argument (`line.main`) for placing the title.

**Comment by dankelley** [comment]
This issue seems to have gone stale, so I'm closing it.
