### ISSUE TITLE
missing method ganttAddTask

### ISSUE THREAD

**Issue by Pietie68** [dankelley/plan#16]
The R package example at http://dankelley.github.io/plan/examples.html refers to ganttAddTask, but I  installed the package and this method is not available.

Please assist

**Comment by dankelley** [comment]
You need to install the development version to get that. Do as follows to install:
```R
library(devtools)
install_github("dankelley/plan", ref="develop")
```

PS. Sorry for the delay in seeing this.

**Comment by peti** [comment]
Would it be possible to release the current development version to CRAN?

**Comment by dankelley** [comment]
Yes, I'll look into a CRAN release. I will add some more tests, to prevent erroneous documentation items such as that you've found.  These releases take a few days, but likely by early next week it will be on CRAN (unless it gets rejected -- always a possibility). Thanks.

**Comment by dankelley** [comment]
I've submitted an update to CRAN and it is gradually being built up on the various platforms (see https://cran.r-project.org/web/checks/check_results_plan.html). I think this may take several days.

With this, I think the issue has been addressed and so I'll close it. I hope the reporter will feel free to reopen it (once checking with the updated CRAN, of course).
