### ISSUE TITLE
Formatting help

### ISSUE THREAD

**Issue by daniellenewby** [dankelley/plan#28]
Hi, 
This package is so good and really useful! :)  I am a little stuck trying to format the x axis labels and titles and was wondering if i could get some help resolving this?  I want to 1) force a label not let the package decide on what labels to show and 2) switch the direction of the labels of the x axis labels so they are vertical 3) I want to add a title to the x axis i.e. months. 

So i was wondering if there were settings like xlab = "Months" and las = 3 for the x axis labels for example. Also in the plot produced in the code above i want to include M3, M9, M15 etc . Attached the code and the output below and thanks for any help with this!

```
g <- new("gantt")
g <- ganttAddTask(g, "Study 1: Bidirectional MR")
g <- ganttAddTask(g, "Data Curation", "2000-01-01", "2000-03-01", done = 100)
g <- ganttAddTask(g, "Genetic Instrument Selection", "2000-03-01", "2000-09-01", done = 100)
g <- ganttAddTask(g, "Dataset Harmonization", "2000-09-01", "2000-11-01", done = 100)
g <- ganttAddTask(g, "Bidirectional MR Analysis", "2000-11-01", "2001-01-01", done = 100)
g <- ganttAddTask(g, "Sensitivity Analysis", "2001-01-01", "2001-03-01", done = 100)
g <- ganttAddTask(g, "Writeup", "2001-03-01", "2001-05-01", done = 100)
g <- ganttAddTask(g, "Study 2: Drug Target MR")
g <- ganttAddTask(g, "Drug Target Identification", "2001-05-01", "2001-06-01", done = 0)
g <- ganttAddTask(g, "Genetic Instrument Selection", "2001-06-01", "2001-09-01", done = 0)
g <- ganttAddTask(g, "Cis-MR Analysis", "2001-09-01", "2002-01-01", done = 0)
g <- ganttAddTask(g, "Sensitivity analysis", "2002-01-01", "2002-04-01", done = 0)
g <- ganttAddTask(g, "Colocalization analysis", "2002-04-01", "2002-10-01", done = 0)
g <- ganttAddTask(g, "Writeup", "2002-10-01", "2003-01-01", done = 0)


plan::plot(g,
  ylabel = list(font = ifelse(is.na(g[["start"]]), 2, 1)),
  event.time = c("2001-01-01", "2002-01-01"),
  xlim = c("2000-01-01", "2003-01-01"),
  col.done = c("blue"),
  col.notdone = c("red"),
  axes  = TRUE, 
  time.format = paste("M", (seq(0, 36, by = 3)), sep = "") 

)

```

![Gannt_chart](https://user-images.githubusercontent.com/16097637/171367080-11953881-fa45-4601-8621-52116771f65e.png)

**Comment by dankelley** [comment]
I'll number what I think are your requests.
1. something about labels, which I don't understand.
2. rotate labels on x axis.  Use `las=2` in the plot call.
3. title for the x axis. This will require setting aside enough space for the axis, and then using`mtext()` but exactly where you place that mtext will depend on the plot geometry, and so you are advised to plot to a device with specified geometry, and then experiment.

Click Details to see my attempts at what I can understand.

<details>

**R code**

```R
png("plan01.png", unit="in", res=200, width=7, height=5)
library(plan)
g <- new("gantt")
g <- ganttAddTask(g, "Study 1: Bidirectional MR")
g <- ganttAddTask(g, "Data Curation", "2000-01-01", "2000-03-01", done = 100)
g <- ganttAddTask(g, "Genetic Instrument Selection", "2000-03-01", "2000-09-01", done = 100)
g <- ganttAddTask(g, "Dataset Harmonization", "2000-09-01", "2000-11-01", done = 100)
g <- ganttAddTask(g, "Bidirectional MR Analysis", "2000-11-01", "2001-01-01", done = 100)
g <- ganttAddTask(g, "Sensitivity Analysis", "2001-01-01", "2001-03-01", done = 100)
g <- ganttAddTask(g, "Writeup", "2001-03-01", "2001-05-01", done = 100)
g <- ganttAddTask(g, "Study 2: Drug Target MR")
g <- ganttAddTask(g, "Drug Target Identification", "2001-05-01", "2001-06-01", done = 0)
g <- ganttAddTask(g, "Genetic Instrument Selection", "2001-06-01", "2001-09-01", done = 0)
g <- ganttAddTask(g, "Cis-MR Analysis", "2001-09-01", "2002-01-01", done = 0)
g <- ganttAddTask(g, "Sensitivity analysis", "2002-01-01", "2002-04-01", done = 0)
g <- ganttAddTask(g, "Colocalization analysis", "2002-04-01", "2002-10-01", done = 0)
g <- ganttAddTask(g, "Writeup", "2002-10-01", "2003-01-01", done = 0)


plan::plot(g,
  ylabel = list(font = ifelse(is.na(g[["start"]]), 2, 1)),
  event.time = c("2001-01-01", "2002-01-01"),
  xlim = c("2000-01-01", "2003-01-01"),
  col.done = c("blue"),
  col.notdone = c("red"),
  axes  = TRUE, 
  las=2,
  maiAdd=c(0.5,0,0,0),
  time.format = paste("M", (seq(0, 36, by = 3)), sep = "") 
)

line <- 2.5 # adjust this
mtext("label for x axis", side=1, line=line)
dev.off()
```

**Results**

![plan01](https://user-images.githubusercontent.com/99469/171380062-a7994bb3-0a2b-4022-89d8-5481f74177f9.png)

**Comment by daniellenewby** [comment]
Hey Dan, Thank you so much for getting back to me so quickly! Those changes are perfect and what i needed so thank you :) The point 1 i was being daft and basically, if i reduce the text size of the x-axis labels then all my label points show (its been a long week). Thank you so much for your help i really appreciate it!

**Comment by dankelley** [comment]
Good to hear you're making progress.  If you think this issue has been addressed, please consider closing it. (I use open issues as a sort of "to do" list.)
