### ISSUE TITLE
Plan gantt charts - shape of event bar

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#4]
Can plan be modified to allow user to change shape of event bar with arrow at one end or other to indicate ongoing even?

**Comment by dankelley** [comment]
I don't really know what you mean. Any chance you could (a) install the latest develop branch, (b) create and print a gantt chart, (c) use a pen to write what you'd like to see and (d) scan or phone-photo and post here? (I think you should be able to attach images without problem, but possibly they need to be PNG format.) Then I'll know better whether I can help. Thanks.

**Comment by marcel111** [comment]
OK, I uploaded an image of a gantt chart produced by plan with some annotations for some of the  new features that would be helpful. This issue refers to item 2 in the figure, which shows an event in the gantt chart that goes on indefinitely, and therefore has a rightward-pointing arrow.   

![samplegantt](https://cloud.githubusercontent.com/assets/14862665/10149009/c141a40c-65eb-11e5-96ec-1285bc11d2a3.jpg)

**Comment by dankelley** [comment]
Thanks, that diagram is very useful.  I think you accidentally closed the issue, so I'm opening it again. These things will all be great additions. I'll plug away at them as I get time.

NOTE: the legend will "come for free" once I alter ``plot.gantt()`` to avoid its resetting ``par`` to initial values, because then the user can just use the R command ``legend()`` to get such things.

**Comment by dankelley** [comment]
FYI, I copied your very helpful diagram to the wiki (at https://github.com/dankelley/plan/wiki/marcel111-diagram-of-hoped-for-plot-capabilities) so that it won't be buried within an issue.

**Comment by dankelley** [comment]
I've done something that might help, in `develop`. See example 8 for `?"plot,gantt-method"`, which produces as shown below. NOTE: the geometry of the triangle is not the best. Right now, it just extends some fraction of the plot width. I think it should maybe be at a 45deg angle or something, but that requires just a bit more fiddling with coordinate systems (which means that the results will be wrong for RStudio OSX, and OSX is my own platform so I prefer not to try).

<img width="806" alt="screen shot 2016-05-21 at 2 53 29 pm" src="https://cloud.githubusercontent.com/assets/99469/15449970/280c795a-1f64-11e6-81d3-acc4ce1d35d4.png">

**Comment by marcel111** [comment]
Thanks this works great!
