### ISSUE TITLE
Plan gantt chart - significant dates timeline

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#6]
Can plan be modified to allow representation of one or more annotated significant dates (e.g, "project due", "steering committee meeting") all on a single line at the top or bottom of the chart.

**Comment by dankelley** [comment]
I don't really know what you mean. Any chance you could (a) install the latest ``develop`` branch, (b) create and print a gantt chart, (c) use a pen to write what you'd like to see and (d) scan or phone-photo and post here?  (I think you should be able to attach images without problem, but possibly they need to be PNG format.) Then I'll know better whether I can help. Thanks.

**Comment by dankelley** [comment]
I wonder if `events` are what you want? See `help("plot,gantt-method")`, example 2.

**Comment by dankelley** [comment]
I've added some text to the `plot,gantt-method` docs (in `develop` branch) to explain a bit more the distinction between events and tasks.

**Comment by dankelley** [comment]
If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!
