### ISSUE TITLE
Simultaneously showing multiple graphs in R

### ISSUE THREAD

**Issue by Dmill7** [dankelley/plan#8]
I am running into a few issues with the plotting of my Gantt chart. Granted, my chart is unusual, but it would be awesome if I could find a way to do it.  This is R, I'm sure a way exists!

This is my goal for how the chart itself will look.  This is a sample working record for an employee, and I'd like to create one week at a time, even though I only drew it with 2 days.
![goal](https://cloud.githubusercontent.com/assets/13008569/10856232/90d4ff9a-7f03-11e5-8ffc-58caea882267.PNG)

I would also like to display more than one record per window. Just to clarify, this is similar to what I am trying to do (either 1x2 or 3x3, depending). 
![samplepossible](https://cloud.githubusercontent.com/assets/13008569/10856300/0f4f885e-7f04-11e5-987d-867e3ef2e049.jpg)

Unfortunately, whenever I try par(mfrow=c(3,3)) or split.screen or layout, this is what happens: 
![sample 3](https://cloud.githubusercontent.com/assets/13008569/10856325/40ee06a6-7f04-11e5-9d33-96e179ad1ca2.jpeg)
 

If you run all of the following code, you should be able to recreate my questions. 

I only need lines with duration longer than 2 minutes, so:
Gantt <- subset(AssemblyGantt, duration > .001389)

I am sure there is a more efficient way to write code like what follows, but I'm very unpracticed.

AA = subset(Gantt, Gantt$Operator.name=="AFA")
AB = subset(Gantt, Gantt$Operator.name=="AB")
DL = subset(Gantt, Gantt$Operator.name=="DL")
DCH = subset(Gantt, Gantt$Operator.name=="DCH")
GY = subset(Gantt, Gantt$Operator.name=="GY")
GS = subset(Gantt, Gantt$Operator.name=="GS")
GC = subset(Gantt, Gantt$Operator.name=="GC")
HT = subset(Gantt, Gantt$Operator.name=="HT")
JO = subset(Gantt, Gantt$Operator.name=="JO")

GanttAA = as.gantt(AA$Key, AA$description, AA$start, AA$end)
GanttAB = as.gantt(AB$Key, AB$description, AB$start, AB$end)
GanttDL = as.gantt(DL$Key, DL$description, DL$start, DL$end)
GanttDCH = as.gantt(DCH$Key, DCH$description, DCH$start, DCH$end)
GanttGY = as.gantt(GY$Key, GY$description, GY$start, GY$end)
GanttGS = as.gantt(GS$Key, GS$description, GS$start, GS$end)
GanttGC = as.gantt(GC$Key, GC$description, GC$start, GC$end)
GanttHT = as.gantt(HT$Key, HT$description, HT$start, HT$end)
GanttJO = as.gantt(JO$Key, JO$description, JO$start, JO$end)

plot(GanttAA, col.notdone="white")
title(main=AA$Operator.name[c(1,0)])
plot(GanttAB, col.notdone="antiquewhite2")
title(main=AB$Operator.name[c(1,0)])
plot(GanttDL, col.notdone="bisque2")
title(main=DL$Operator.name[c(1,0)])
plot(GanttDCH, col.notdone="blanchedalmond")
title(main=DCH$Operator.name[c(1,0)])
plot(GanttGY, col.notdone="burlywood")
title(main=GY$Operator.name[c(1,0)])
plot(GanttGS, col.notdone="burlywood4")
title(main=GS$Operator.name[c(1,0)])
plot(GanttGC, col.notdone="chartreuse2")
title(main=GC$Operator.name[c(1,0)])
plot(GanttHT, col.notdone="chocolate1")
title(main=HT$Operator.name[c(1,0)])
plot(GanttJO, col.notdone="coral")
title(main=JO$Operator.name[c(1,0)])

par(mfrow=c(2,2))
plot(GanttGS, col.notdone="burlywood4")	
title(main=GS$Operator.name[c(1,0)])
plot(GanttGC, col.notdone="chartreuse2")
title(main=GC$Operator.name[c(1,0)])
plot(GanttHT, col.notdone="chocolate1")
title(main=HT$Operator.name[c(1,0)])
plot(GanttJO, col.notdone="coral")
title(main=JO$Operator.name[c(1,0)])

**Comment by dankelley** [comment]
I'm sorry this has been unaddressed for such a long time. I do not see how to make this work. R is tricky, in terms of how it handles multiple figures.  For example, `layout()`, `par(mfrow)`, and `split.screen()` all attempt to permit the user to have multiple figures, but they cannot be used together in a sensible way.

The `gantt` diagram in `plan` is drawn with some tricky actions to place things in the margins. I am not too surprised that it fails to work well with figure-combining setups. Fixing it could be tricky, partly because popular platforms (RStudio vs others) handle figure geometry differently.

I simply cannot set aside the time that would be required to try to fix this issue. Therefore, with regret and not just for leaving this pending for so long, I am closing this issue.
